### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by 1071942338** [johnno1962/injectionforxcode#108] opened 2016-03-20 04:02 UTC
I install this by Alcatraz.First,patch to my projec.Second,change the view's backgroudcolor . Third inject source.But,it do not work.The console as below,

2016-03-20 11:57:58.870 NotificationTest[2135:91902] +[BundleInjection load] 192.168.1.102 (see project's main.(m|mm)
2016-03-20 11:57:58.874 NotificationTest[2135:92018] Injection attempting connection to: 127.0.0.1:31442
2016-03-20 11:57:58.875 NotificationTest[2135:92018] Connected to "Injection" plugin, ready to load x86_64 code.
Compiling /Users/zhangwenqi/Desktop/测试/NotificationTest/NotificationTest/ViewController.m
        0.45 real         0.03 user         0.27 sys
objc[2135]: Class ViewController is implemented in both /Users/zhangwenqi/Library/Developer/CoreSimulator/Devices/E0E4BE9B-87AE-4F72-864C-468FFCBC68AE/data/Containers/Bundle/Application/7B630B7F-4FB7-442F-9AD1-7E03529C982A/NotificationTest.app/NotificationTest and /Users/zhangwenqi/Desktop/测试/NotificationTest/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle. One of the two will be used. Which one is undefined.
15 injections performed so far.
2016-03-20 11:58:54.143 NotificationTest[2135:91902] Ignore any warning, Swizzled ViewController 0x1131f92e8 -> 0x108d67c48

'control '+ '='  and 'control '+'shift'+ '=' do the same work.How can I solve this problem?

**Comment by orta** [comment] 2016-03-20 07:59
Looks like a duplicate of https://github.com/johnno1962/injectionforxcode/issues/108

**Closed by orta** 2016-03-20 07:59 UTC
